# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.box = "precise64"
  config.vm.box_url = "http://files.vagrantup.com/precise64.box"
		#Setup for web server
		config.vm.define "web" do |web|
				web.vm.hostname = "web"
				web.vm.box = "apache"
				web.vm.network "private_network", type: "dhcp"
				web.vm.network "forwarded_port", guest: 80, host: 8092
				web.vm.provision "puppet" do |puppet|
						puppet.manifests_path = "manifests"
						# Please note below diff for manifest
						puppet.manifest_file = "default.pp"
		end
end
		#Setup for MySQL server
		config.vm.define "db" do |db|
				db.vm.hostname = "db"
				db.vm.box = "mysql"
				db.vm.network "private_network", type: "dhcp"
		end
end
