# This Docker File will create image which will execute echo command only

FROM centos:latest
MAINTAINER Prasanth.Katta@gmail.com
RUN adduser -ms /bin/bash user
CMD "echo" "This Is a custom container Message for Mr Prasanth Katta"
