# This Docker File will install system update, Telnet and OpenSSHD-server

FROM ubuntu:xenial
MAINTAINER Prasanth Katta <Prasanth.Katta@gmail.com>
RUN apt-get update
RUN apt-get install -y telnet openssh-server
