--- # install based on os type

- name: Based on OS type will install Nginx server
  hosts: dev
  user: prasanth_ansible
  gather_facts: yes
  tasks:
  - name: get facts
    group_by: key={{ ansible_distribution }}
    register: out
  - debug: var=out['add_group']

- name: Nginx Installation on Centos
  hosts: CentOS
  user: prasanth_ansible
  become: yes
  gather_facts: no
  tasks:
  - name: Installing nginx
    yum: pkg=nginx state=latest update_cache=yes
    notify: Restart nginx
    register: nginx_install_c
  - debug: var=nginx_install_c
  handlers:
  - name: Restart nginx
    tags:
    - restartnginx
    action: service name=nginx state=restarted
    register: out_c
  - debug: var=out_c

- name: Nginx Installation on Ubuntu
  hosts: Ubuntu
  user: prasanth_ansible
  become: yes
  gather_facts: no
  tasks:
  - name: Installing Nginx Server
    apt: name=nginx state=latest update_cache=yes
    notify: Restart nginx
    register: nginx_install_u
  - debug: var=nginx_install_u
  handlers:
  - name: Restart nginx
    tags:
    - restartnginx
    action: service name=nginx state=restarted
    register: out_u
  - debug: var=out_u

