--- # install based on os type

- name: Based on OS type will install the sw
  hosts: dev
  user: prasanth_ansible
  gather_facts: yes
  tasks:
  - name: get facts
    group_by: key={{ ansible_distribution }}
    register: out
  - debug: var=out['add_group']

- name: Installation on Centos
  hosts: CentOS
  user: prasanth_ansible
  become: yes
  gather_facts: no
  tasks:
  - name: Installing HTTPD
    yum: pkg=httpd state=latest
    notify: Restart HTTPD
  handlers:
  - name: Restart HTTPD
    service: name=httpd state=restarted

- name: Installation on Ubuntu
  hosts: Ubuntu
  user: prasanth_ansible
  become: yes
  gather_facts: no
  tasks:
  - name: Installing Apache Server
    apt: name=apache2 state=latest
    notify: Restart Apache
  handlers:
  - name: Restart Apache
    service: name=apache2 state=restarted
