--- 

- hosts: dev
  user: prasanth
  become: yes
  connection: ssh
  gather_facts: no
  vars:
    ansible_playbook_version: 0.1b
  vars_files:
    - conf/copyright.yml
    - conf/apache_common.yml
  vars_prompt:
    - name: Web_Domain
      prompt: Web Domain
  tasks:
    - name: Installing Nginx Server On Dev Node
      action: yum name=nginx state=installed
      notify: Restart Nginx
  handlers:
    - name: Restart Nginx
      action: service name=nginx state=restarted
